name: Docker Image CI for GHCR

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u c0s1nus -p ${{ secrets.GH_PAT }} ghcr.io
        docker build -t ghcr.io/c0s1nus/aitomaton-priceparser:${{ github.sha }} .
        docker push ghcr.io/c0s1nus/aitomaton-priceparser:${{ github.sha }}
